### ISSUE TITLE
No micro menu

### ISSUE THREAD

**Issue by KronemeyerJoshua** [blooblahguy/bdActionbars#4]
I love this addon, but there's no micromenu! :/
Intended or..?

**Comment by gladelynch** [comment]
Intended, but there is a bdActionsbars rewrite on the horizon where I intend to add this and a lot more functionality. Will leave this issue open as a reminder

**Comment by blub0r** [comment]
Is there any new information about micromenu? The horizon in sight :)? 
Love the bdStuff, good work guy(s) 👍

**Comment by gladelynch** [comment]
MicroMenu is in the latest update. A little unpolished but at the very least you can change its size and turn it on/off in the configuration.
